#//*
# //  * @project_name : WALLYJAYTECH-MD
# //  * @author : wallyjaytechy
# //  * @youtube : https://www.youtube.com/@wallyjaytechy
#//   * @description : WALLYJAYTECH-V3 ,A Multi-functional whatsapp user bot.
#//*
#//* 
#//base by WALLYJAYTECH-MD
#//re-upload? recode? copy code? give credit ya :)
#//Instagram: wallyjaytechy
#//Telegram: t.me/wallyjaytechy
#//GitHub: @wallyjaytechy
#//WhatsApp: +2348144317152
#//want more free bot scripts? subscribe to my youtube channel: https://youtube.com/@wallyjaytechy
#//   * Created By Github: Wally Jay Tech.
#//   * Credit To Wallyjaytech
#//   * © 2024 WALLYJAYTECH-MD.
#// ⛥┌┤
#// */


 

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/SuhailTechInfo/Suhail-Md-V4 /root/smdd
RUN rm -rf /root/smdd/.git
WORKDIR /root/smdd
RUN npm install || yarn install
EXPOSE 8000
CMD ["npm","start" ] 



# heroku.yml file data to run Container
# build:
#   docker:
#       web: Wallyjaytech_Md
# run:
#   web: npm start
 
